---
include:
  - board: praxis_he
    snippet: "cdc-acm-console zmk-analog-matrix-calibrator"
    artifact-name: praxis_he_calibrator
  - board: praxis_he
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: praxis_he_studio
